on: [push]

jobs:
  test:
    runs-on: codeberg-tiny
    strategy:
      matrix:
        crystal-version: ['1.14', 'latest']
    container:
      image: crystallang/crystal:${{ matrix.crystal-version }}
    steps:
      - run: git clone --depth 1 --branch ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }} .

      - run: shards install
      - run: crystal spec
      - run: crystal tool format --check
      - run: bin/ameba
